// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/theQRL/qrysm/v4/validator/client/iface (interfaces: SlasherClient)

// Package validator_mock is a generated GoMock package.
package validator_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	zond "github.com/theQRL/qrysm/v4/proto/prysm/v1alpha1"
)

// MockSlasherClient is a mock of SlasherClient interface.
type MockSlasherClient struct {
	ctrl     *gomock.Controller
	recorder *MockSlasherClientMockRecorder
}

// MockSlasherClientMockRecorder is the mock recorder for MockSlasherClient.
type MockSlasherClientMockRecorder struct {
	mock *MockSlasherClient
}

// NewMockSlasherClient creates a new mock instance.
func NewMockSlasherClient(ctrl *gomock.Controller) *MockSlasherClient {
	mock := &MockSlasherClient{ctrl: ctrl}
	mock.recorder = &MockSlasherClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlasherClient) EXPECT() *MockSlasherClientMockRecorder {
	return m.recorder
}

// IsSlashableAttestation mocks base method.
func (m *MockSlasherClient) IsSlashableAttestation(arg0 context.Context, arg1 *zond.IndexedAttestation) (*zond.AttesterSlashingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlashableAttestation", arg0, arg1)
	ret0, _ := ret[0].(*zond.AttesterSlashingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSlashableAttestation indicates an expected call of IsSlashableAttestation.
func (mr *MockSlasherClientMockRecorder) IsSlashableAttestation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlashableAttestation", reflect.TypeOf((*MockSlasherClient)(nil).IsSlashableAttestation), arg0, arg1)
}

// IsSlashableBlock mocks base method.
func (m *MockSlasherClient) IsSlashableBlock(arg0 context.Context, arg1 *zond.SignedBeaconBlockHeader) (*zond.ProposerSlashingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlashableBlock", arg0, arg1)
	ret0, _ := ret[0].(*zond.ProposerSlashingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSlashableBlock indicates an expected call of IsSlashableBlock.
func (mr *MockSlasherClientMockRecorder) IsSlashableBlock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlashableBlock", reflect.TypeOf((*MockSlasherClient)(nil).IsSlashableBlock), arg0, arg1)
}
