// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/qrysm/v1alpha1/validator-client/web_api.proto

package validatorpb

import (
	context "context"
	reflect "reflect"
	sync "sync"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated: Marked as deprecated in proto/qrysm/v1alpha1/validator-client/web_api.proto.
type KeymanagerKind int32

const (
	KeymanagerKind_DERIVED    KeymanagerKind = 0
	KeymanagerKind_IMPORTED   KeymanagerKind = 1
	KeymanagerKind_REMOTE     KeymanagerKind = 2
	KeymanagerKind_WEB3SIGNER KeymanagerKind = 3
)

// Enum value maps for KeymanagerKind.
var (
	KeymanagerKind_name = map[int32]string{
		0: "DERIVED",
		1: "IMPORTED",
		2: "REMOTE",
		3: "WEB3SIGNER",
	}
	KeymanagerKind_value = map[string]int32{
		"DERIVED":    0,
		"IMPORTED":   1,
		"REMOTE":     2,
		"WEB3SIGNER": 3,
	}
)

func (x KeymanagerKind) Enum() *KeymanagerKind {
	p := new(KeymanagerKind)
	*p = x
	return p
}

func (x KeymanagerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeymanagerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes[0].Descriptor()
}

func (KeymanagerKind) Type() protoreflect.EnumType {
	return &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes[0]
}

func (x KeymanagerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeymanagerKind.Descriptor instead.
func (KeymanagerKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in proto/qrysm/v1alpha1/validator-client/web_api.proto.
type ExportSlashingProtectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *ExportSlashingProtectionResponse) Reset() {
	*x = ExportSlashingProtectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportSlashingProtectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSlashingProtectionResponse) ProtoMessage() {}

func (x *ExportSlashingProtectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSlashingProtectionResponse.ProtoReflect.Descriptor instead.
func (*ExportSlashingProtectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP(), []int{0}
}

func (x *ExportSlashingProtectionResponse) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/qrysm/v1alpha1/validator-client/web_api.proto.
type ImportSlashingProtectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlashingProtectionJson string `protobuf:"bytes,1,opt,name=slashing_protection_json,json=slashingProtectionJson,proto3" json:"slashing_protection_json,omitempty"`
}

func (x *ImportSlashingProtectionRequest) Reset() {
	*x = ImportSlashingProtectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportSlashingProtectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSlashingProtectionRequest) ProtoMessage() {}

func (x *ImportSlashingProtectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSlashingProtectionRequest.ProtoReflect.Descriptor instead.
func (*ImportSlashingProtectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP(), []int{1}
}

func (x *ImportSlashingProtectionRequest) GetSlashingProtectionJson() string {
	if x != nil {
		return x.SlashingProtectionJson
	}
	return ""
}

var File_proto_qrysm_v1alpha1_validator_client_web_api_proto protoreflect.FileDescriptor

var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc = []byte{
	0x0a, 0x33, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x72, 0x79, 0x73, 0x6d, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x77, 0x65, 0x62, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x74, 0x68, 0x65, 0x71, 0x72, 0x6c, 0x2e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x32, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a,
	0x0a, 0x20, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x3a, 0x02, 0x18, 0x01, 0x22, 0x5f, 0x0a, 0x1f, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a,
	0x18, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x16, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4a, 0x73, 0x6f, 0x6e, 0x3a, 0x02, 0x18, 0x01, 0x2a, 0x4b, 0x0a, 0x0e, 0x4b,
	0x65, 0x79, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x45, 0x52, 0x49, 0x56, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4d,
	0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f,
	0x54, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x45, 0x42, 0x33, 0x53, 0x49, 0x47, 0x4e,
	0x45, 0x52, 0x10, 0x03, 0x1a, 0x02, 0x18, 0x01, 0x32, 0xea, 0x02, 0x0a, 0x12, 0x53, 0x6c, 0x61,
	0x73, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0xa7, 0x01, 0x0a, 0x18, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69,
	0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x3e, 0x2e, 0x74, 0x68, 0x65, 0x71, 0x72, 0x6c, 0x2e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x32, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69,
	0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f, 0x76,
	0x32, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x6c, 0x61, 0x73,
	0x68, 0x69, 0x6e, 0x67, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x88, 0x02, 0x01, 0x12, 0xa9, 0x01, 0x0a, 0x18, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x2e, 0x74, 0x68, 0x65, 0x71, 0x72, 0x6c, 0x2e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x6c, 0x61, 0x73,
	0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x36, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x2d, 0x3a, 0x01, 0x2a, 0x22, 0x28, 0x2f, 0x76, 0x32, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x88, 0x02, 0x01, 0x42, 0xba, 0x01, 0x0a, 0x20, 0x6f, 0x72, 0x67, 0x2e, 0x74, 0x68,
	0x65, 0x71, 0x72, 0x6c, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x32, 0x42, 0x08, 0x57, 0x65, 0x62, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x51, 0x52, 0x4c, 0x2f, 0x71, 0x72, 0x79, 0x73, 0x6d, 0x2f,
	0x76, 0x34, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x72, 0x79, 0x73, 0x6d, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x3b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x70, 0x62, 0xaa, 0x02, 0x1c, 0x54, 0x68, 0x65, 0x51, 0x52, 0x4c, 0x2e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2e, 0x56, 0x32, 0xca, 0x02, 0x1c, 0x54, 0x68, 0x65, 0x51, 0x52, 0x4c, 0x5c, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x5c,
	0x56, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescData = file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc
)

func file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescData)
	})
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_goTypes = []interface{}{
	(KeymanagerKind)(0),                      // 0: theqrl.validator.accounts.v2.KeymanagerKind
	(*ExportSlashingProtectionResponse)(nil), // 1: theqrl.validator.accounts.v2.ExportSlashingProtectionResponse
	(*ImportSlashingProtectionRequest)(nil),  // 2: theqrl.validator.accounts.v2.ImportSlashingProtectionRequest
	(*emptypb.Empty)(nil),                    // 3: google.protobuf.Empty
}
var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_depIdxs = []int32{
	3, // 0: theqrl.validator.accounts.v2.SlashingProtection.ExportSlashingProtection:input_type -> google.protobuf.Empty
	2, // 1: theqrl.validator.accounts.v2.SlashingProtection.ImportSlashingProtection:input_type -> theqrl.validator.accounts.v2.ImportSlashingProtectionRequest
	1, // 2: theqrl.validator.accounts.v2.SlashingProtection.ExportSlashingProtection:output_type -> theqrl.validator.accounts.v2.ExportSlashingProtectionResponse
	3, // 3: theqrl.validator.accounts.v2.SlashingProtection.ImportSlashingProtection:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_validator_client_web_api_proto_init() }
func file_proto_qrysm_v1alpha1_validator_client_web_api_proto_init() {
	if File_proto_qrysm_v1alpha1_validator_client_web_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportSlashingProtectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportSlashingProtectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_validator_client_web_api_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_validator_client_web_api_proto_depIdxs,
		EnumInfos:         file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes,
		MessageInfos:      file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_validator_client_web_api_proto = out.File
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc = nil
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SlashingProtectionClient is the client API for SlashingProtection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SlashingProtectionClient interface {
	// Deprecated: Do not use.
	ExportSlashingProtection(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ExportSlashingProtectionResponse, error)
	// Deprecated: Do not use.
	ImportSlashingProtection(ctx context.Context, in *ImportSlashingProtectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type slashingProtectionClient struct {
	cc grpc.ClientConnInterface
}

func NewSlashingProtectionClient(cc grpc.ClientConnInterface) SlashingProtectionClient {
	return &slashingProtectionClient{cc}
}

// Deprecated: Do not use.
func (c *slashingProtectionClient) ExportSlashingProtection(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ExportSlashingProtectionResponse, error) {
	out := new(ExportSlashingProtectionResponse)
	err := c.cc.Invoke(ctx, "/theqrl.validator.accounts.v2.SlashingProtection/ExportSlashingProtection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *slashingProtectionClient) ImportSlashingProtection(ctx context.Context, in *ImportSlashingProtectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/theqrl.validator.accounts.v2.SlashingProtection/ImportSlashingProtection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlashingProtectionServer is the server API for SlashingProtection service.
type SlashingProtectionServer interface {
	// Deprecated: Do not use.
	ExportSlashingProtection(context.Context, *emptypb.Empty) (*ExportSlashingProtectionResponse, error)
	// Deprecated: Do not use.
	ImportSlashingProtection(context.Context, *ImportSlashingProtectionRequest) (*emptypb.Empty, error)
}

// UnimplementedSlashingProtectionServer can be embedded to have forward compatible implementations.
type UnimplementedSlashingProtectionServer struct {
}

func (*UnimplementedSlashingProtectionServer) ExportSlashingProtection(context.Context, *emptypb.Empty) (*ExportSlashingProtectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSlashingProtection not implemented")
}
func (*UnimplementedSlashingProtectionServer) ImportSlashingProtection(context.Context, *ImportSlashingProtectionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSlashingProtection not implemented")
}

func RegisterSlashingProtectionServer(s *grpc.Server, srv SlashingProtectionServer) {
	s.RegisterService(&_SlashingProtection_serviceDesc, srv)
}

func _SlashingProtection_ExportSlashingProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlashingProtectionServer).ExportSlashingProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.validator.accounts.v2.SlashingProtection/ExportSlashingProtection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlashingProtectionServer).ExportSlashingProtection(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlashingProtection_ImportSlashingProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSlashingProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlashingProtectionServer).ImportSlashingProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.validator.accounts.v2.SlashingProtection/ImportSlashingProtection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlashingProtectionServer).ImportSlashingProtection(ctx, req.(*ImportSlashingProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SlashingProtection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "theqrl.validator.accounts.v2.SlashingProtection",
	HandlerType: (*SlashingProtectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportSlashingProtection",
			Handler:    _SlashingProtection_ExportSlashingProtection_Handler,
		},
		{
			MethodName: "ImportSlashingProtection",
			Handler:    _SlashingProtection_ImportSlashingProtection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qrysm/v1alpha1/validator-client/web_api.proto",
}
