// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.1
// source: proto/qrl/v1/version.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Version int32

const (
	Version_ZOND Version = 0
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0: "ZOND",
	}
	Version_value = map[string]int32{
		"ZOND": 0,
	}
)

func (x Version) Enum() *Version {
	p := new(Version)
	*p = x
	return p
}

func (x Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrl_v1_version_proto_enumTypes[0].Descriptor()
}

func (Version) Type() protoreflect.EnumType {
	return &file_proto_qrl_v1_version_proto_enumTypes[0]
}

func (x Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrl_v1_version_proto_rawDescGZIP(), []int{0}
}

var File_proto_qrl_v1_version_proto protoreflect.FileDescriptor

var file_proto_qrl_v1_version_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x72, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x68,
	0x65, 0x71, 0x72, 0x6c, 0x2e, 0x71, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2a, 0x16, 0x0a, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x41, 0x50, 0x45, 0x4c, 0x4c,
	0x41, 0x10, 0x00, 0x42, 0x69, 0x0a, 0x11, 0x6f, 0x72, 0x67, 0x2e, 0x74, 0x68, 0x65, 0x71, 0x72,
	0x6c, 0x2e, 0x71, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x51, 0x52, 0x4c, 0x2f, 0x71, 0x72, 0x79, 0x73,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x72, 0x6c, 0x2f, 0x76, 0x31, 0xaa, 0x02,
	0x0d, 0x54, 0x68, 0x65, 0x51, 0x52, 0x4c, 0x2e, 0x51, 0x52, 0x4c, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x0d, 0x54, 0x68, 0x65, 0x51, 0x52, 0x4c, 0x5c, 0x51, 0x52, 0x4c, 0x5c, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_qrl_v1_version_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_version_proto_rawDescData []byte
)

func file_proto_qrl_v1_version_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_version_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_version_proto_rawDesc), len(file_proto_qrl_v1_version_proto_rawDesc)))
	})
	return file_proto_qrl_v1_version_proto_rawDescData
}

var file_proto_qrl_v1_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_qrl_v1_version_proto_goTypes = []any{
	(Version)(0), // 0: theqrl.qrl.v1.Version
}
var file_proto_qrl_v1_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_version_proto_init() }
func file_proto_qrl_v1_version_proto_init() {
	if File_proto_qrl_v1_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_version_proto_rawDesc), len(file_proto_qrl_v1_version_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_version_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_version_proto_depIdxs,
		EnumInfos:         file_proto_qrl_v1_version_proto_enumTypes,
	}.Build()
	File_proto_qrl_v1_version_proto = out.File
	file_proto_qrl_v1_version_proto_goTypes = nil
	file_proto_qrl_v1_version_proto_depIdxs = nil
}
